Классификация текстовых отзывов тесла по классам Отрицательные, положительные, нейтральные.



In [ ]:
# Токенизатор для преобразование текстов в последовательности
from tensorflow.keras.preprocessing.text import Tokenizer
# Функции-утилиты для работы с категориальными данными
from tensorflow.keras import utils,regularizers
# Работа с массивами данных
import numpy as np 
# Класс для конструирования последовательной модели нейронной сети
from tensorflow.keras.models import Sequential
# Основные слои
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Activation ,Embedding,SpatialDropout1D,Flatten,Input,LSTM,Conv1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam
# Функции операционной системы
import os
# Регулярные выражения
import re
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
import zipfile
import xml.etree.ElementTree

WORD_NAMESPACE = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
PARA = WORD_NAMESPACE + 'p'
TEXT = WORD_NAMESPACE + 't'
TABLE = WORD_NAMESPACE + 'tbl'
ROW = WORD_NAMESPACE + 'tr'
CELL = WORD_NAMESPACE + 'tc'

with zipfile.ZipFile('Tesla 1.docx') as docx:
    tree = xml.etree.ElementTree.XML(docx.read('word/document.xml'))

for table in tree.iter(TABLE):
    for row in table.iter(ROW):
        for cell in row.iter(CELL):
            print(''.join(node.text for node in cell.iter(TEXT)))

FileNotFoundError: ignored

In [ ]:
!pip install docx2txt
import docx2txt
text1 = docx2txt.process("Tesla 1.docx")
text2 = docx2txt.process("Tesla 2.docx")
text1.replace('\xa0','')
text2.replace('\xa0','')
text1.replace('.','')
text2.replace('.','')

  Created wheel for docx2txt: filename=docx2txt-0.8-py3-none-any.whl size=3980 sha256=a7c6806069bf6d3d8e80e604515d6a6de85ebbfdf847a57b868a1cb16de676a9
  Stored in directory: /root/.cache/pip/wheels/b7/20/b2/473e3aea9a0c0d3e7b2f7bd81d06d0794fec12752733d1f3a8
Successfully built docx2txt


'+ Моментальная реакция, Весело управляется (юркая и быстрая), Быстро заряжается (принимает до 250 кВт), Хорошо тормозит двигателем (тормоз не нужен), Постоянно обновляется ПО через интернет, Передний багажник, Привлекает взгляды\n\n- Центральная консоль быстро марается, Неудобные дверные ручки, Нет Apple Car Play и Android Auto\n\n+- Я и сам вожу модель3, правда в Калифорнии, в принципе машина весьма и весьма средняя, хотя дешевизна владения подкупает Много минусов, но стоимость владения конечно решает Друг предложил купить его МоделС (он брал в свое время новую за 125К), у меня был бы лайфтайм суперчардж, но при этом я бы не получил никаких кредитов и ребейтов Вобщем купил, не жалею, но и не рад Жопу возить машина, радости не приносит\n\n+ Тесла топ,а не машина\n\n+ Машина Тесла красотка,для наших дорог -самое то\n\n+ Надо брать!\n\n+ Тесла-очень удобная машина!\n\n+ Миниатюрная и потребляет не много\n\n+- для тех кто будет покупать машину: НЕ берите стандартный звук - разница между 

In [ ]:
text1_list=text1.split('\n')
text1_list=[item for item in text1_list if item!='']
print(len(text1_list))
text2_list=text2.split('\n')
text2_list=[item for item in text2_list if item!='']
print(len(text2_list))

2497
2481


In [ ]:
print(text1_list[:10])

['+ Водитель наслаждается от такого авто и вождения', '+ Красивая машина нужно брать', '+ Тесла топ, тащусь от этой тачки', '+-Машина на любителя. Назвать мягкой её сложно. Двери открывающиеся вверх неудобны.\xa0', '- После 170 на трассе она чувствует себя неуверенно.\xa0', '+Плюсы - зарядка бесплатная.\xa0', '+- Третий ряд - есть у многих. Возможно \xa0технологичность и берет верх, но бензиновый двигатель это ... классика, мужская классика. А Тесла - как зауженные брюки))). Говорю именно про Икс', '- Кстати сидения очень удобными тоже не назовёшь. ... Это моё личное впечатление об автомобиле.', '+Машина топ Технологии по автоматизации не стоят на месте!', '+Красивая машина нужно брать']


Парсинг данных, разбивка на классы.

In [ ]:
# y1 -1  0  1  y2  + 1,0 -0,1 +- 1,1  y3 +1,0,0 - 0,0,1  +- 0,1,0
x_data_text=[]
y_data1=[]
y_data2=[]
y_data3=[]
for item in text1_list:
  if(item[:2]=='+ '):
    x_data_text.append(item[2:])
    y_data1.append(np.array(1))
    y_data2.append(np.array((1,0)))
    y_data3.append(np.array((1,0,0)))
  elif(item[:2]=='- '):
    x_data_text.append(item[2:])
    y_data1.append(np.array(-1))
    y_data2.append(np.array((0,1)))
    y_data3.append(np.array((0,0,1)))
  elif(item[:2]=='+-' or item[:2]=='-+'):
    text=item[2:]
    if(text[0]==' '):
      text=text[1:]
    x_data_text.append(text)
    y_data1.append(np.array(0))
    y_data2.append(np.array((1,1)))
    y_data3.append(np.array((0,1,0)))
for item in text2_list:
  if(item[:2]=='+ '):
    x_data_text.append(item[2:])
    y_data1.append(np.array(1))
    y_data2.append(np.array((1,0)))
    y_data3.append(np.array((1,0,0)))
  elif(item[:2]=='- '):
    x_data_text.append(item[2:])
    y_data1.append(np.array(-1))
    y_data2.append(np.array((0,1)))
    y_data3.append(np.array((0,0,1)))
  elif(item[:2]=='+-' or item[:2]=='-+'):
    text=item[2:]
    if(text[0]==' '):
      text=text[1:]
    x_data_text.append(text)
    y_data1.append(np.array(0))
    y_data2.append(np.array((1,1)))
    y_data3.append(np.array((0,1,0)))
y_data1=np.array(y_data1)
y_data1=y_data1.reshape((-1,1))
y_data2=np.array(y_data2)
y_data3=np.array(y_data3)
print(len(x_data_text))
print(y_data1.shape,y_data2.shape,y_data3.shape)

4891
(4891, 1) (4891, 2) (4891, 3)


In [ ]:
print(x_data_text[:5])

['Водитель наслаждается от такого авто и вождения', 'Красивая машина нужно брать', 'Тесла топ, тащусь от этой тачки', 'Машина на любителя. Назвать мягкой её сложно. Двери открывающиеся вверх неудобны.\xa0', 'После 170 на трассе она чувствует себя неуверенно.\xa0']


In [ ]:
VOCAB_SIZE=20000
# Токенайзер из Keras для разбиения текста и построения частотного словаря
tokenizer = Tokenizer(num_words=VOCAB_SIZE, filters='!"#$%&()*+,-–—./…:;<=>?@[\\]^_`{|}~«»\t\n\xa0\ufeff', 
                          lower=True, split=' ', oov_token='неизвестное_слово', char_level=False)

In [ ]:
# Получаем словарь частотности 
tokenizer.fit_on_texts(x_data_text)

In [ ]:
seq_train = tokenizer.texts_to_sequences(x_data_text)

In [ ]:
print(y_data1[:5])
print(y_data2[:5])
print(y_data3[:5])

[[ 1]
 [ 1]
 [ 1]
 [ 0]
 [-1]]
[[1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#Обрубим отзывы до 17 слов и дополним нулями если не хватает
SequencyWords=17
train_data = pad_sequences(seq_train, maxlen=SequencyWords, padding='post', truncating='post') 

Проверка баланса классов.

In [ ]:
print("class0=",np.shape(y_data1[y_data1==-1]))
print("class1=",np.shape(y_data1[y_data1==0]))
print("class2=",np.shape(y_data1[y_data1==1]))

class0= (1152,)
class1= (1568,)
class2= (2171,)


In [ ]:
print(train_data.shape,y_data1.shape,y_data2.shape,y_data3.shape)

(4891, 17) (4891, 1) (4891, 2) (4891, 3)


Желательно сбалансировать. попробуем балансировку весами при обучении.

In [ ]:
train_data_balance=train_data.copy()
y_data1_balance=y_data1.copy()
y_data2_balance=y_data2.copy()
y_data3_balance=y_data3.copy()
add_c0=2171-1152
add_c1=2171-1568
train_data_balance=np.vstack((train_data_balance,train_data[y_data1[:,0]==-1][:add_c0,:]))
y_data1_balance=np.vstack((y_data1_balance,y_data1[y_data1[:,0]==-1][:add_c0].reshape(-1,1)))
y_data2_balance=np.vstack((y_data2_balance,y_data2[y_data1[:,0]==-1][:add_c0]))
y_data3_balance=np.vstack((y_data3_balance,y_data3[y_data1[:,0]==-1][:add_c0]))
train_data_balance=np.vstack((train_data_balance,train_data[y_data1[:,0]==0][:add_c1,:]))
y_data1_balance=np.vstack((y_data1_balance,y_data1[y_data1==0][:add_c1].reshape(-1,1)))
y_data2_balance=np.vstack((y_data2_balance,y_data2[y_data1[:,0]==0][:add_c1]))
y_data3_balance=np.vstack((y_data3_balance,y_data3[y_data1[:,0]==0][:add_c1]))
print("class0=",np.shape(y_data1_balance[y_data1_balance==-1]))
print("class1=",np.shape(y_data1_balance[y_data1_balance==0]))
print("class2=",np.shape(y_data1_balance[y_data1_balance==1]))

class0= (2171,)
class1= (2171,)
class2= (2171,)


In [ ]:
print(train_data_balance.shape,y_data1_balance.shape,y_data2_balance.shape,y_data3_balance.shape)

(6513, 17) (6513, 1) (6513, 2) (6513, 3)


In [ ]:
train_data[y_data1[:,0]==-1][:add_c0,:].shape

(1019, 17)

Сверточная модель

In [ ]:
l2Conv=0.03
l2Dense=0.03

input = Input((SequencyWords))
x = Embedding(VOCAB_SIZE, 20)(input)
x = SpatialDropout1D(0.2)(x)
x = Conv1D(8,3, activation="relu",kernel_regularizer=regularizers.l2(l2Conv))(x)#,bias_regularizer=regularizers.l2(l2Conv)
x = Flatten()(x)
#x=Dense(100, activation="relu")(x)
#x = BatchNormalization()(x)
x = Dropout(0.5)(x)
x = Dense(30, activation="relu",kernel_regularizer=regularizers.l2(l2Conv))(x)
#x = BatchNormalization()(x)
#x = Dropout(0.5)(x)
#x = Dense(33, activation="relu",kernel_regularizer=regularizers.l2(l2Conv))(x)
x = BatchNormalization()(x)
x = Dropout(0.1)(x)
y1= Dense(1,activation='tanh')(x)
y2= Dense(2,activation='sigmoid')(x)
y3= Dense(3,activation='softmax')(x)

model=Model(input,[y1,y2,y3])
model.compile(loss='mse',metrics=['accuracy'], optimizer=Adam(learning_rate=1e-4))

In [ ]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_3 (InputLayer)           [(None, 17)]         0           []                               
                                                                                                  
 embedding_2 (Embedding)        (None, 17, 20)       400000      ['input_3[0][0]']                
                                                                                                  
 spatial_dropout1d_2 (SpatialDr  (None, 17, 20)      0           ['embedding_2[0][0]']            
 opout1D)                                                                                         
                                                                                                  
 conv1d_2 (Conv1D)              (None, 15, 8)        488         ['spatial_dropout1d_2[0][0]

In [ ]:
model.fit(train_data_balance, [y_data1_balance,y_data2_balance,y_data3_balance],validation_split=0.05, epochs = 60, batch_size = 128)#,class_weight=class_weight

Epoch 1/60
49/49 [==============================] - 2s 16ms/step - loss: 3.3847 - dense_9_loss: 1.0648 - dense_10_loss: 0.2893 - dense_11_loss: 0.2650 - dense_9_accuracy: 0.3121 - dense_10_accuracy: 0.4980 - dense_11_accuracy: 0.3430 - val_loss: 2.2082 - val_dense_9_loss: 8.1851e-04 - val_dense_10_loss: 0.2461 - val_dense_11_loss: 0.2260 - val_dense_9_accuracy: 1.0000 - val_dense_10_accuracy: 0.4080 - val_dense_11_accuracy: 0.1227
Epoch 2/60
49/49 [==============================] - 1s 11ms/step - loss: 3.2279 - dense_9_loss: 0.9825 - dense_10_loss: 0.2785 - dense_11_loss: 0.2593 - dense_9_accuracy: 0.3275 - dense_10_accuracy: 0.5080 - dense_11_accuracy: 0.3417 - val_loss: 2.1413 - val_dense_9_loss: 9.5200e-04 - val_dense_10_loss: 0.2397 - val_dense_11_loss: 0.2227 - val_dense_9_accuracy: 1.0000 - val_dense_10_accuracy: 0.4755 - val_dense_11_accuracy: 0.2883
Epoch 3/60
49/49 [==============================] - 1s 11ms/step - loss: 3.0762 - dense_9_loss: 0.9017 - dense_10_loss: 0.2748 - d

LSTM

In [ ]:
input = Input((SequencyWords))
x = Embedding(VOCAB_SIZE, 100)(input)
x = SpatialDropout1D(0.2)(x)
x = LSTM(10)(x)
x = Dropout(0.5)(x)
x = Dense(33, activation="relu")(x)
#x = BatchNormalization()(x)
x = Dropout(0.1)(x)
y1= Dense(1,activation='tanh')(x)
y2= Dense(2,activation='sigmoid')(x)
y3= Dense(3,activation='softmax')(x)

model=Model(input,[y1,y2,y3])
model.compile(loss='mse', metrics=['accuracy'], optimizer=Adam(learning_rate=1e-4))
model.summary()

Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, 17)]         0           []                               
                                                                                                  
 embedding_5 (Embedding)        (None, 17, 100)      2000000     ['input_6[0][0]']                
                                                                                                  
 spatial_dropout1d_5 (SpatialDr  (None, 17, 100)     0           ['embedding_5[0][0]']            
 opout1D)                                                                                         
                                                                                                  
 lstm_2 (LSTM)                  (None, 10)           4440        ['spatial_dropout1d_5[0][0]

In [ ]:
model.fit(train_data_balance, [y_data1_balance,y_data2_balance,y_data3_balance],validation_split=0.05, epochs = 60, batch_size = 128)#,class_weight=class_weight

Epoch 1/60
49/49 [==============================] - 5s 46ms/step - loss: 1.1721 - dense_19_loss: 0.7013 - dense_20_loss: 0.2486 - dense_21_loss: 0.2222 - dense_19_accuracy: 0.2982 - dense_20_accuracy: 0.5660 - dense_21_accuracy: 0.3239 - val_loss: 0.4687 - val_dense_19_loss: 2.1612e-04 - val_dense_20_loss: 0.2442 - val_dense_21_loss: 0.2243 - val_dense_19_accuracy: 1.0000 - val_dense_20_accuracy: 0.8313 - val_dense_21_accuracy: 0.0123
Epoch 2/60
49/49 [==============================] - 2s 35ms/step - loss: 1.1685 - dense_19_loss: 0.6989 - dense_20_loss: 0.2474 - dense_21_loss: 0.2222 - dense_19_accuracy: 0.2982 - dense_20_accuracy: 0.5633 - dense_21_accuracy: 0.3241 - val_loss: 0.4673 - val_dense_19_loss: 7.5370e-04 - val_dense_20_loss: 0.2402 - val_dense_21_loss: 0.2263 - val_dense_19_accuracy: 1.0000 - val_dense_20_accuracy: 0.8098 - val_dense_21_accuracy: 0.0031
Epoch 3/60
49/49 [==============================] - 2s 34ms/step - loss: 1.1646 - dense_19_loss: 0.6962 - dense_20_loss: 0

In [ ]:
Prediction=model.predict(train_data)
print(Prediction[0].shape)
print(Prediction[1].shape)
print(Prediction[2].shape)



(4891, 1)
(4891, 2)
(4891, 3)


Матрица классификации.

In [ ]:
Prediction3=np.argmax(Prediction[2],axis=1)

In [ ]:
PrecMatrix=np.zeros((3,3))
summ=np.zeros((3))
for i in range(Prediction3.shape[0]):
  PrecMatrix[np.argmax(y_data3[i]),Prediction3[i]]+=1
  summ[np.argmax(y_data3[i])]+=1

In [ ]:
print(PrecMatrix/summ)

[[0.98894519 0.01403061 0.00173611]
 [0.00783049 0.97193878 0.0234375 ]
 [0.         0.00382653 0.99479167]]
