Решение уравнения с помощью генетического алгоритма.

Используя генетический алгоритм, найдите корни уравнения:

$f(xy)=7x^2 - y + \frac{y^3 - x^2}{3x} + y^2 - 21x$

*P.s. постарайтесь по максимуму использовать возможности библиотеки numpy для ускорения процеесса вычислений*

**Решение**

In [ ]:
import numpy as np  
import random
import matplotlib.pyplot as plt

In [ ]:
# Задание рабочей функции
def f(x, y):
    return 7*pow(x,2)-y+(pow(y,3)-pow(x,2))/3/x+pow(y,2)-21*x

In [ ]:
# Задание длины бота
botlength = 6

# Задание размера популяции
populationlength = 1000

# Задание стартового значения мутации
mutation = 0.6

# Задание количества выживших
nsurv = 200

# Задаем количество новых ботов
nnew = populationlength - nsurv

# Задание количества эпох
epochs = 100

In [ ]:
def fbybot(bot):
    # Расчет значения x
    x = bot[0] + 10*bot[1] + 100*bot[2]

    # Расчет значения y
    y = bot[3] + 10*bot[4] + 100*bot[5]

    # Возвращаем значение функции
    return f(x, y)

In [ ]:
# Создание популяции
population = np.random.uniform(-10, 10, size=(populationlength, botlength))

In [ ]:
# Запускаем цикл обучения
for epoch in range(1, epochs):
    # Уменьшаем мутацию
    if epoch %10 == 0:
        mutation*= 0.5
    # Расчет ошибок ботов
    val = np.array(list(map(fbybot, population)))
    sortIndex=np.argsort(np.abs(val))

    # Получение лучших ботов из популяции
    newpopul = population[sortIndex[:nsurv]]

    # Выводим 5 лучших ботов
    if epoch %2 == 0:
        print(f'{epoch}   {[round(s,8) for s in val[sortIndex][0:5]]}')

    # Генерируем случайные пары родителей и индекс для каждого элемента
    parents = np.array([np.random.choice(np.random.randint(0, nsurv, 2),2) for _ in range(nnew)])#.reshape(-1)
    newbots=[]
    for i in range(parents.shape[0]):
      newbot=[]
      for geneNum in range(botlength):
        newbot.append(newpopul[np.random.choice(parents[i])][geneNum])
      newbots.append(newbot)
    newbots=np.array(newbots)

    
    indexesmut = np.random.choice(
        [False, True],
        size = newbots.shape[0],
        p=[1-mutation, mutation])
    
    # Производим выборочную мутацию по сгенерированным индексам
    newbots[indexesmut] += 2*np.random.random(newbots[indexesmut].shape) - 1.0
    newpopul=np.vstack((newpopul,newbots))
    
    # Обновляем популяцию
    population = newpopul.copy()

2   [-286.18618074, -286.18618074, -286.18618074, -542.49104046, 1227.56080189]
4   [2.84048771, 111.09246388, 113.33080114, 131.17808397, -286.18618074]
6   [2.84048771, 2.84048771, -19.68064967, 42.33759033, -83.82668704]
8   [2.84048771, 2.84048771, 6.10418366, 6.10418366, 12.21489195]
10   [1.95507815, 2.84048771, 2.84048771, 2.84048771, 2.84048771]
12   [-0.39515225, 1.95507815, 1.95507815, 1.95507815, 2.84048771]
14   [-0.39515225, -0.39515225, -0.39515225, -0.39515225, -0.39515225]
16   [-0.30563496, -0.39515225, -0.39515225, -0.39515225, -0.39515225]
18   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
20   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
22   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
24   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
26   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
28   [-0.30563496, -0.30563496, -0.30563496, -0.30563496, -0.30563496]
30   [-0.

In [ ]:
bot=population[0]
x = bot[0] + 10*bot[1] + 100*bot[2]
y = bot[3] + 10*bot[4] + 100*bot[5]
print(x,y,f(x, y))

2.292090862372291 -4.963230637437093 -0.3056349633957183


Сошелся на решении.

Дальше тесты

In [ ]:
 val = np.array(list(map(fbybot, population)))
 sortIndex=np.argsort(np.abs(val))

In [ ]:
val[sortIndex[:200]]

array([   1394.38140236,    3263.42596124,    5894.40287164,
          7302.56246004,   -7888.00268672,   -9693.00916001,
        -11963.83506266,   12273.80456046,  -14381.50863477,
        -17461.13580749,   18197.91628805,   18425.96625619,
         21322.46202845,  -25486.31941451,   27150.99592844,
         29242.50062163,   29700.94818381,  -37622.70741031,
         38100.83329565,   41198.33943289,  -43747.88563235,
         44522.46870537,   44805.72698025,   45564.7407513 ,
         47012.14572108,   51525.5885534 ,  -51580.8224938 ,
         54539.59844981,   55237.99953343,   72764.96784744,
        -73109.89958606,   82330.31265568,  -88530.12911452,
         96776.73879201,   97672.33165258,  105494.14760805,
       -105626.08003664,  110205.35165953,  115322.22009716,
        115340.89519156,  117850.24387439,  120514.2691533 ,
        120869.44548792,  121800.89430055,  128961.16448946,
        130681.63787184,  132686.29564097,  134057.08738242,
        135329.13739036,

In [ ]:
parents = np.array([np.random.choice(np.random.randint(0, nsurv, 2),botlength) for _ in range(nnew)]).reshape(-1)

In [ ]:
val = np.array(list(map(fbybot, population)))
sortIndex=np.argsort(np.abs(val))
newpopul = population[sortIndex[:nsurv]]
parents = np.array([np.random.choice(np.random.randint(0, nsurv, 2),2) for _ in range(nnew)])#.reshape(-1)


In [ ]:
newbots=[]
for i in range(parents.shape[0]):
      newbot=[]
      for geneNum in range(botlength):
        newbot.append(newpopul[np.random.choice(parents[i])][geneNum])
      newbots.append(newbot)
newbots=np.array(newbots)

In [ ]:
newbots[0]

array([ 0.09265873,  4.10607089, -2.44789526,  6.91140562,  4.83856045,
       -0.65171655])

In [ ]:
[np.random.choice(np.random.randint(0, nsurv, 2),2),np.random.choice(np.random.randint(0, nsurv, 2),2)]

array([151, 151])

In [ ]:
indexesmut = np.random.choice(
        [False, True],
        size = newbots.shape[0],
        p=[1-mutation, mutation])

In [ ]:
indexesmut[:10]

array([ True,  True, False,  True,  True, False,  True,  True,  True,
       False])

In [ ]:
np.random.choice(np.random.randint(0, nsurv, 2),botlength)

array([153, 194, 194, 153, 153, 194])

In [ ]:
newpopul[np.random.choice(parents[i])][geneNum]

ValueError: ignored

In [ ]:
np.random.choice(parents[i])

ValueError: ignored

In [ ]:
parents

array([ 23,  63,  74, ...,  78, 152, 104])